version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_tarik_tambang
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tariktambangdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - tariknet

  web:
    build: .
    container_name: flask_tarik_tambang
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: tariktambangdb
    networks:
      - tariknet

networks:
  tariknet:

volumes:
  mysql_data:
